namespace: "argo" # default
serviceAccountName: "argo-workflows" # default
resources:
  limits:
    cpu: '1'
    memory: 100Mi
  requests: {}
storage:
  key: "argo-workflows" # default
  bucket: "ai-datastore" # required
  region: "eu-west-1" # required
  endpoint: "s3.amazonaws.com" # default

  accessKeySecret: # default
    name: "argo-secret"
    key: "ARGO_WORKFLOWS_ACCESS"

  secretKeySecret: # default
    name: "argo-secret"
    key: "ARGO_WORKFLOWS_SECRET"